# Generated by Django 6.0.3 on 2026-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('electronics', 'Elektronika'), ('clothing', 'Odzież'), ('books', 'Książki'), ('food', 'Żywność'), ('other', 'Inne')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
